[project]
name = "web_semantique"
version = "0.1.0"
description = "TP Web semantique"
authors = [
    {name = "Matthieu LAURENT"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "None"}


[tool.pdm]
distribution = false
